apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf-custom
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf-custom
  template:
    metadata:
      labels:
        app: audiobookshelf-custom
    spec:
      containers:
      - name: audiobookshelf
        image: ghcr.io/deyinka07/azure-aks-gitops-platform/audiobookshelf-custom:latest
        ports:
        - containerPort: 80
        env:
        - name: AUDIOBOOKSHELF_UID
          value: "1000"
        - name: AUDIOBOOKSHELF_GID
          value: "1000"
